version: '3.7'

volumes:
  ts-db:

services:
  ts-postgres:
    container_name: test-db-2024
    image: postgres:15.1-alpine
    restart: always
    environment:
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: test-db
    volumes:
      - ts-db:/var/lib/postgresql/data
#      - ./data:/var/lib/postgresql/data
#      - ./data:/tmp/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5437:5432"
